### ISSUE TITLE
Bug: Cursed Equipment/Curse Breaking

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#60]
I wore-IDed a lantern of flickering shadows, and invested in Will/Curse Breaking to remove it, but after taking Curse Breaking I noticed that my light doesn't appear to be in the equipment listing when I go to [t]ake it off.

**Comment by ThatGitMITZE** [comment]
Same situation with a cursed weapon; this time had a _Sanctity, no effect and like before the cursed object's slot isn't displayed under [t]ake off.

**Comment by NickMcConnell** [comment]
Probably fixed in 011b98c62.

**Comment by NickMcConnell** [comment]
Yep, looks done.

**Comment by backwardsEric** [comment]
I'm still seeing this.  With the Curse Breaking ability, a character can drop an equipped cursed item but can not take it off (because obj_can_takeoff() prevents it from showing up as a possible target for the take off command).  Sil 1.3's code allows both take off and drop to work with an equipped cursed item when the character has the Curse Breaking ability (at the cost of duplicated logic in do_cmd_takeoff() and do_cmd_drop()).
